version: "3"

services:
  app-client:
    container_name: app-client
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev
    tty: true
    volumes:
      - type: bind
        source: .
        target: /app
      - escape_node_modules:/node_modules
    restart: always
    ports:
      - 3030:3030
    networks:
      - go_plactice_network_client
    stdin_open: true

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  go_plactice_network_client:
    external: true

volumes:
  escape_node_modules:
